name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run 
      run: cargo run
    - name: make file
      run: |
        touch new_file.png
        cat "${{ github.action_path }}output.png" > new_file.png
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: Changed files
