name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Uploaded Image
    - uses: actions/upload-artifact@v3
      with:
           name: image.png
           path: out/image.png
