name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run 
      run: cargo run
    - name: make file
      run: |
        touch new_file.png
        cat "${{ github.action_path }}output.png" > new_file.png
      shell: bash
    - uses: EndBug/add-and-commit@v9
      with:
          message: commit output image
          committer_name: GitHub Actions
          committer_email: actions@github.com
