name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
    contents: write
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run 
      run: cargo run
    - name: create output folder
      run: |
          mkdir -p action_output
      shell: bash
    - name: copy output file from run
      run: |
        touch action_output/action_output_image.png
        cat "${{ github.action_path }}output.png" > action_output/action_output_image.png
      shell: bash
    - name: remove output file from run
      run: |
        if [ -f ${{ github.action_path }}output.png ]; then
           rm ${{ github.action_path }}output.png
           echo "Output file removed."
        fi        
      shell: bash
    - uses: EndBug/add-and-commit@v9
      with:
          message: commit output image
          committer_name: GitHub Actions
          committer_email: actions@github.com
